### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by cpetit-sigma-fr** [bflorat/cours-licences.github.io#1]
Even if the project's license is in the main file (CC-BY-SA 4.0), there should be a LICENSE file at project's root.

**Comment by bflorat** [comment]
Merci Chips ;-)

**Comment by cpetit-sigma-fr** [comment]
File should be called LICENSE ;-)

**Comment by bflorat** [comment]
I asked myself because the lesson content is in French but, I guess you're right : the license content being in English, it makes sense to use the English word. Thanks.
